version: '2'
services:
    raitamitra-app:
        image: raitamitra
        external_links:
            - raitamitra-mysql:mysql
            - raitamitra-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/raitamitra?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    raitamitra-mysql:
        extends:
            file: mysql.yml
            service: raitamitra-mysql
    raitamitra-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: raitamitra-elasticsearch
